export const adminTypes = {
  AUTHENTICATE_REQUEST: "AUTHENTICATE_REQUEST",
  AUTHENTICATE_SUCCESS: "AUTHENTICATE_SUCCESS",
  AUTHENTICATE_FAILURE: "AUTHENTICATE_FAILURE",
  REGISTER_REQUEST: "REGISTER_REQUEST", // New action type
  REGISTER_SUCCESS: "REGISTER_SUCCESS", // New action type
  REGISTER_FAILURE: "REGISTER_FAILURE",
};
